/**
 * Telemetry envelope — v0 (XC-004)
 * ================================
 *
 * This module is the **locked** v0 telemetry event schema for Pulse. Every
 * participant- or persona-generated event (post, reply, reaction, view, DM,
 * login, engine action, ...) is eventually captured against this envelope.
 *
 * Why this file is unusually conservative: the adversarial review
 * (`docs/11-ADVERSARIAL-REVIEW.md`, finding D2) flagged that "a schema
 * mistake becomes a cross-phase migration" — E10's metrics, E9's event
 * stream (`INT-031`), and E8's observation loop all read this same taxonomy
 * later. The envelope's **core fields are closed** (fixed shape below); new
 * event kinds/data extend it via the **open** `eventType` string and the
 * `payload` extension point — never by changing this envelope's shape
 * without a version bump (`schemaVersion` is a literal `'v0'` for exactly
 * this reason).
 *
 * Source of truth: `telemetryEventV0Schema` (zod). `TelemetryEventV0` (and
 * every sibling type below) is *derived* from the schema via `z.infer`, so
 * the runtime validator and the compile-time type can never drift apart —
 * there is deliberately no separately hand-maintained interface to keep in
 * sync.
 *
 * Decoupling note (Wave 0): this module does not import
 * `core/exerciseContext` or `core/clock` (the other two Wave-0 foundation
 * seams). Callers (features that emit events) are responsible for sourcing
 * `exerciseId`/`timeZone` from the exercise context and `scenarioTime` from
 * the scenario clock, and passing them in — see `emitter.ts`.
 *
 * Participant-visibility note: `origin` and `injectId` exist for
 * provenance/attribution (controller-as-persona vs. genuine participant
 * action vs. an injected event) and are **never rendered on a participant
 * surface** (see `posts/03-post-provenance.md`). This module has no read
 * path at all — only a future staff/evaluator surface may display them.
 */

import { z } from 'zod'

// ---------------------------------------------------------------------------
// Sub-schemas
// ---------------------------------------------------------------------------

/** The channel/surface an event originated on or targets. */
export const telemetryChannelSchema = z.enum([
  'social',
  'portal',
  'news',
  'press',
  'weather',
  'system',
])
export type TelemetryChannel = z.infer<typeof telemetryChannelSchema>

/** What kind of actor produced the event. */
export const telemetryActorKindSchema = z.enum([
  'participant',
  'persona',
  'system',
  'engine',
])
export type TelemetryActorKind = z.infer<typeof telemetryActorKindSchema>

/**
 * Provenance of the event — e.g. whether a persona post was actually typed
 * by a controller live ("controller-as-persona") vs. generated by the
 * engine vs. queued as a scripted inject. **Never participant-visible.**
 */
export const telemetryOriginSchema = z.enum([
  'participant',
  'controller-as-persona',
  'engine',
  'inject',
])
export type TelemetryOrigin = z.infer<typeof telemetryOriginSchema>

/**
 * The actor block. `actingHumanId` carries the individual human behind a
 * shared org/controller account (COR-018, per-human attribution) and
 * `sessionId` is an ephemeral read-only session identity used for reach
 * counting (COR-015). All identifiers beyond `kind` are optional — not
 * every actor kind populates every field (e.g. `system`/`engine` actors
 * have no `participantId`).
 */
export const telemetryActorSchema = z.object({
  kind: telemetryActorKindSchema,
  participantId: z.string().min(1).optional(),
  personaId: z.string().min(1).optional(),
  actingHumanId: z.string().min(1).optional(),
  sessionId: z.string().min(1).optional(),
  role: z.string().min(1).optional(),
})
export type TelemetryActor = z.infer<typeof telemetryActorSchema>

/** Optional pointer to the entity an event acted on (a post, an article, ...). */
export const telemetryTargetSchema = z.object({
  entityType: z.string().min(1).optional(),
  entityId: z.string().min(1).optional(),
})
export type TelemetryTarget = z.infer<typeof telemetryTargetSchema>

/**
 * A string that must parse as a valid date-time (ISO-8601 in practice — see
 * each field's doc comment below for the exact flavor expected). Deliberately
 * validated via `Date.parse` rather than zod's stricter `z.iso.datetime()`
 * regex so the v0 schema doesn't reject reasonable ISO-8601 variants (e.g. a
 * numeric offset instead of a trailing `Z`) before this seam has real
 * callers to observe.
 */
const isoDateTimeString = z
  .string()
  .min(1, 'must be a non-empty date-time string')
  .refine(value => !Number.isNaN(Date.parse(value)), {
    message: 'must be a valid ISO-8601 date-time string',
  })

// ---------------------------------------------------------------------------
// The v0 envelope (locked)
// ---------------------------------------------------------------------------

/**
 * The v0 telemetry event envelope, exactly as locked in
 * `docs/features/telemetry/01-telemetry-emitter-v0.md`:
 *
 * ```ts
 * interface TelemetryEventV0 {
 *   schemaVersion: 'v0'
 *   eventId: string
 *   exerciseId: string
 *   eventType: string
 *   channel: 'social' | 'portal' | 'news' | 'press' | 'weather' | 'system'
 *   actor: { kind, participantId?, personaId?, actingHumanId?, sessionId?, role? }
 *   origin?: 'participant' | 'controller-as-persona' | 'engine' | 'inject'
 *   injectId?: string
 *   wallClockTime: string
 *   scenarioTime: string
 *   timeZone: string
 *   target?: { entityType?, entityId? }
 *   payload?: Record<string, unknown>
 *   emittedAt: string
 * }
 * ```
 */
export const telemetryEventV0Schema = z.object({
  /** Literal — a future breaking change is a new literal, never a mutation of this one. */
  schemaVersion: z.literal('v0'),
  /** uuid; client-generated — see `buildTelemetryEvent`. */
  eventId: z.string().min(1),
  /** REQUIRED, non-empty — isolation scope (COR-001/XC-001). Never omit. */
  exerciseId: z.string().min(1, 'exerciseId is required'),
  /**
   * Open string — see `KNOWN_TELEMETRY_EVENT_TYPES` below for the
   * documented Phase-1 vocabulary. Deliberately NOT a zod enum: later
   * features (notably the E8 engine event types) extend this vocabulary
   * additively, with no envelope migration.
   */
  eventType: z.string().min(1),
  channel: telemetryChannelSchema,
  actor: telemetryActorSchema,
  /** Provenance — NEVER rendered on a participant surface. */
  origin: telemetryOriginSchema.optional(),
  /** Set when `origin === 'inject'`. Provenance — never participant-visible. */
  injectId: z.string().min(1).optional(),
  /** ISO-8601 UTC — real (wall-clock) time. Telemetry-only; never shown in-fiction. */
  wallClockTime: isoDateTimeString,
  /** ISO-8601 scenario time (COR-053) — what participants would see, if this were ever shown. */
  scenarioTime: isoDateTimeString,
  /** IANA time zone of the exercise (XC-008), e.g. `America/Chicago`. */
  timeZone: z.string().min(1),
  target: telemetryTargetSchema.optional(),
  /** Event-type-specific extension point. */
  payload: z.record(z.string(), z.unknown()).optional(),
  /** ISO-8601 UTC — when the emitter stamped/sent the event (see `buildTelemetryEvent`). */
  emittedAt: isoDateTimeString,
})

/**
 * The v0 telemetry event. Derived from `telemetryEventV0Schema` — do not
 * hand-author a parallel interface for this; it would be able to silently
 * drift from the runtime validator.
 */
export type TelemetryEventV0 = z.infer<typeof telemetryEventV0Schema>

// ---------------------------------------------------------------------------
// Phase-1 known `eventType` vocabulary (documentation only)
// ---------------------------------------------------------------------------

/**
 * The Phase-1 known `eventType` vocabulary. This is **documentation only** —
 * `telemetryEventV0Schema.eventType` stays a plain, open `z.string()` so
 * later features can extend the vocabulary additively with no envelope
 * migration. Notably, `engine-telemetry-tuning` later adds engine event
 * types (`engine.observed` / `decided` / `generated` / `reviewed` /
 * `published` / `measured`, `storyline.state_changed`, and the reserved
 * `rumor.*` family) on top of this same list.
 */
export const KNOWN_TELEMETRY_EVENT_TYPES = [
  'post',
  'reply',
  'reaction',
  'repost',
  'quote',
  'article_view',
  'press_release',
  'dm',
  'login',
  'logout',
  'follow',
  'view',
  'search',
  'steering_action',
] as const

/**
 * Convenience union of the Phase-1 known event types, handy for autocomplete
 * when constructing an event. `TelemetryEventV0['eventType']` remains a
 * plain `string` — this type is never used to constrain the schema.
 */
export type KnownTelemetryEventType = (typeof KNOWN_TELEMETRY_EVENT_TYPES)[number]
