// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pulse.WebApi.Data;

#nullable disable

namespace Pulse.WebApi.Data.Migrations
{
    [DbContext(typeof(PulseDbContext))]
    partial class PulseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pulse.WebApi.Data.Entities.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("Pulse.WebApi.Data.Entities.Persona", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PersonaTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("Pulse.WebApi.Data.Entities.PersonaTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PersonaTemplates");
                });

            modelBuilder.Entity("Pulse.WebApi.Data.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorPersonaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedScenarioTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MutationOf")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RumorRef")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Pulse.WebApi.Data.Entities.TelemetryEvent", b =>
                {
                    b.Property<string>("EventId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CausationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("EmittedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InjectId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Payload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ScenarioTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("WallClockTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("EventId");

                    b.HasIndex("ExerciseId");

                    b.ToTable("TelemetryEvents");
                });

            modelBuilder.Entity("Pulse.WebApi.Data.Entities.TelemetryEvent", b =>
                {
                    b.OwnsOne("Pulse.WebApi.Data.Entities.TelemetryActor", "Actor", b1 =>
                        {
                            b1.Property<string>("TelemetryEventEventId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("ActingHumanId")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ParticipantId")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PersonaId")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Role")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("SessionId")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TelemetryEventEventId");

                            b1.ToTable("TelemetryEvents");

                            b1.WithOwner()
                                .HasForeignKey("TelemetryEventEventId");
                        });

                    b.OwnsOne("Pulse.WebApi.Data.Entities.TelemetryTarget", "Target", b1 =>
                        {
                            b1.Property<string>("TelemetryEventEventId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("EntityId")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("EntityType")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TelemetryEventEventId");

                            b1.ToTable("TelemetryEvents");

                            b1.WithOwner()
                                .HasForeignKey("TelemetryEventEventId");
                        });

                    b.Navigation("Actor")
                        .IsRequired();

                    b.Navigation("Target");
                });
#pragma warning restore 612, 618
        }
    }
}
