/**
 * features/controller/engine/hooks/useEngineUsage.ts
 * ---------------------------------------------------------------------------
 * The AI-generation usage READ hook (feature: engine-telemetry-tuning, story
 * 03c; ADP-041, D5 §11). STAFF world — pure hook, no UI, no COBRA. Reads
 * `GET /api/engine/usage` (story 03a) — a live-ops volume/cost view over the
 * exercise's `engine.generated` event log, distinct from `useEngineSettings`
 * (which answers "what provider is live NOW", AC1 — this hook never repeats
 * that question; see `<UsagePanel>`'s module header for how the two are kept
 * separate).
 *
 * ## No mutations, so no await-then-apply serialization apparatus
 * Unlike `useEngineSettings` (three mutating endpoints racing on one DTO),
 * this hook only ever GETs — an idempotent read with no side effect to
 * protect. So it deliberately does NOT reuse that hook's full "one request
 * outstanding at a time" queueing model; instead it keeps the ONE guard that
 * model exists to generalize in the first place: a monotonic "latest issued
 * wins on landing" sequence number, so a slow response for an OLDER window
 * selection or an OLDER manual refresh can never overwrite a NEWER one that
 * already landed. Concurrent GETs are allowed to race freely; only landing
 * order is gated. `loading` is a per-exercise IN-FLIGHT COUNT (not a single
 * flag), so it stays `true` for as long as ANY issued request is still
 * outstanding, regardless of how many are in flight at once.
 *
 * ## No auto-refresh polling (deliberate non-goal, per the story)
 * `TelemetryEvents` carries no index on `EventType`, so every read re-scans
 * the exercise's `engine.*` rows — a polling interval would compound that on
 * every tick for every open console. This hook exposes `refresh()` (manual)
 * only; `<UsagePanel>` also calls it once on every OPEN TRANSITION, mirroring
 * `<EngineSettingsPanel>`'s own staleness discipline, but nothing here ever
 * fires on a timer.
 *
 * ## The window (AC2/AC6)
 * `windowMinutes` defaults to the server's own default (60) — deliberately
 * OMITTED from the wire request in that case (`liveEngineUsageActions`'s
 * module header, fact 1: an explicit empty value is a `400`, never a
 * fall-through). Selecting a different preset re-issues a live GET with that
 * value. The window is WALL-CLOCK throughout (COR-053 staff carve-out) — see
 * `EngineUsageWindow.clock`, always `"wall-clock"`, which `<UsagePanel>`
 * labels explicitly rather than leaving a reader to guess the clock.
 *
 * ## MOCK <-> LIVE (`USE_MOCK_DATA`, `@/core/config/mockData`)
 * Mock renders a plausible, DETERMINISTIC snapshot with NO network call,
 * generated by {@link buildMockEngineUsage} for whatever window is currently
 * selected (so the window selector visibly does something even without a
 * backend — useful for UAT, which runs on the mock flag). The mock
 * deliberately exercises every state AC2/AC3/AC8 care about in one snapshot:
 * a priced model (`AzureOpenAI`/`gpt-5.4`, real per-token rates), an UNPRICED
 * model (`AzureOpenAI`/`gpt-5.4-mini`, token counts shown, every cost field
 * `null`), an UNATTRIBUTED row (empty `provider`/`model` — a thin/partly-null
 * stored payload that still cost money), a `re-roll` in the guard mix, and a
 * non-zero `unparseableEvents`. The `Fake` provider row mirrors UAT's real
 * dataset today: real call volume, ZERO tokens (by construction), priced at
 * an honest `$0` (not "unpriced").
 *
 * `refresh()` is a NO-OP under mock (mirrors `useEngineSettings.refetch()` —
 * "there is nothing to refetch") — there is no server to go stale, so
 * re-generating the snapshot on every open-transition/manual-refresh would
 * only discard whatever a test (or a future caller) deliberately injected via
 * `engineUsageStore.setForTests`. `setWindowMinutes` is the one mock path
 * that DOES regenerate — selecting a different window is an explicit user
 * action, the same "instant apply, no server to race" treatment
 * `useEngineSettings`'s mutations get, not a passive freshness ping.
 *
 * ## PER-EXERCISE SCOPE (COR-001)
 * Module-singleton store keyed by `exerciseId` — mirrors `useEngineSettings`'s
 * / `useEngineControl`'s shape (`subscribe`/`resetForTests`), so a remount
 * under a different exercise reads a distinct snapshot and no exercise's
 * usage leaks into another's.
 *
 * ## NO TELEMETRY EMITTED HERE
 * This is a read-only observability surface over an existing event log — it
 * introduces no event of its own (AC "Telemetry (XC-004)").
 */

import { useCallback, useEffect, useSyncExternalStore } from 'react'
import { USE_MOCK_DATA } from '@/core/config/mockData'
import { useExerciseContext } from '@/core/exerciseContext'
import {
  describeUsageError,
  getUsage as fetchUsage,
  type EngineUsageDto,
  type EngineUsageRates,
} from '../services/liveEngineUsageActions'

export type {
  EngineUsageBucket,
  EngineUsageCost,
  EngineUsageDto,
  EngineUsageGuardResult,
  EngineUsageLatency,
  EngineUsageModel,
  EngineUsageModelCost,
  EngineUsageRates,
  EngineUsageTotals,
  EngineUsageWindow,
} from '../services/liveEngineUsageActions'

/**
 * The window presets `<UsagePanel>` offers — every one the backend documents
 * as evenly-bucketed (SG-001).
 */
export const ENGINE_USAGE_WINDOW_PRESETS_MINUTES = [1, 15, 60, 240, 1440] as const

/**
 * The server's own default window (`EngineUsageAggregator.DefaultWindowMinutes`)
 * — sent by OMISSION, never as an explicit value.
 */
export const DEFAULT_WINDOW_MINUTES = 60

const MAX_BUCKETS = 60

// ---------------------------------------------------------------------------
// The mock usage snapshot generator
// ---------------------------------------------------------------------------

/**
 * The geometry {@link buildBucketGeometry} derives from a window — bucket
 * starts + width + the window's own bounds.
 */
interface MockBucketGeometry {
  readonly starts: readonly string[]
  readonly bucketMinutes: number
  readonly fromWallClock: string
  readonly toWallClock: string
}

/**
 * Mirrors `EngineUsageAggregator.BuildWindow`'s bucket-ceiling geometry
 * (server contract, `EngineUsageAggregator.cs`).
 */
function buildBucketGeometry(nowMs: number, windowMinutes: number): MockBucketGeometry {
  const bucketMinutes = Math.max(1, Math.ceil(windowMinutes / MAX_BUCKETS))
  const bucketCount = Math.max(1, Math.ceil(windowMinutes / bucketMinutes))
  const fromMs = nowMs - windowMinutes * 60_000
  const starts: string[] = []
  for (let i = 0; i < bucketCount; i += 1) {
    starts.push(new Date(fromMs + i * bucketMinutes * 60_000).toISOString())
  }
  return {
    starts,
    bucketMinutes,
    fromWallClock: new Date(fromMs).toISOString(),
    toWallClock: new Date(nowMs).toISOString(),
  }
}

/**
 * Deterministically distributes `total` calls across `bucketCount` buckets,
 * weighted toward the MOST RECENT buckets (a burstier, more "live" look than
 * a flat spread) — the remainder always lands on the recency-weighted side so
 * `sum(result) === total` exactly, never approximately.
 */
function recencyWeightedDistribution(bucketCount: number, total: number): number[] {
  if (bucketCount <= 0) return []
  if (total <= 0) return new Array(bucketCount).fill(0)

  const weights = Array.from({ length: bucketCount }, (_, i) => i + 1)
  const weightSum = weights.reduce((sum, w) => sum + w, 0)
  const floored = weights.map(w => Math.floor((w / weightSum) * total))
  let remainder = total - floored.reduce((sum, c) => sum + c, 0)
  for (let i = floored.length - 1; i >= 0 && remainder > 0; i -= 1) {
    floored[i] = (floored[i] ?? 0) + 1
    remainder -= 1
  }
  return floored
}

function bucketsFor(starts: readonly string[], counts: readonly number[]) {
  return starts.map((startWallClock, i) => ({ startWallClock, calls: counts[i] ?? 0 }))
}

/** One synthetic model's shape before its bucket series is attached. */
interface MockModelSeed {
  readonly provider: string
  readonly model: string
  readonly calls: number
  readonly inputTokens: number
  readonly outputTokens: number
  readonly cacheReadInputTokens: number
  readonly cacheCreationInputTokens: number
  readonly latencyTotalMs: number
  readonly latencyMaxMs: number
  readonly guardResults: readonly { readonly result: string; readonly calls: number }[]
  readonly priced: boolean
  readonly rates: EngineUsageRates | null
}

const RATE_UNIT = 1_000_000

function round6(value: number): number {
  return Math.round(value * 1_000_000) / 1_000_000
}

/**
 * Builds a plausible, deterministic `EngineUsageDto` for `windowMinutes` as
 * of `nowMs` — no network call. See this module's header for exactly which
 * states this snapshot exercises and why (AC2/AC3/AC8).
 */
export function buildMockEngineUsage(windowMinutes: number, nowMs: number): EngineUsageDto {
  const { starts, bucketMinutes, fromWallClock, toWallClock } = buildBucketGeometry(
    nowMs,
    windowMinutes,
  )
  const bucketCount = starts.length

  const seeds: readonly MockModelSeed[] = [
    // The Fake provider — mirrors UAT's real dataset today: real volume, ZERO
    // tokens by construction, priced at an honest $0 (never "unpriced" — the
    // price table DOES have an entry, it's just all zeros).
    {
      provider: 'Fake',
      model: 'fake-deterministic',
      calls: 40,
      inputTokens: 0,
      outputTokens: 0,
      cacheReadInputTokens: 0,
      cacheCreationInputTokens: 0,
      latencyTotalMs: 0.8,
      latencyMaxMs: 0.05,
      guardResults: [{ result: 'pass', calls: 40 }],
      priced: true,
      rates: {
        inputPer1MTokens: 0,
        outputPer1MTokens: 0,
        cacheReadPer1MTokens: 0,
        cacheCreationPer1MTokens: 0,
      },
    },
    // A priced live model, including a re-roll (a call that cost money and
    // produced nothing — counted, never dropped).
    {
      provider: 'AzureOpenAI',
      model: 'gpt-5.4',
      calls: 4,
      inputTokens: 8_000,
      outputTokens: 2_000,
      cacheReadInputTokens: 300,
      cacheCreationInputTokens: 40,
      latencyTotalMs: 9_200,
      latencyMaxMs: 3_100,
      guardResults: [
        { result: 'pass', calls: 3 },
        { result: 're-roll', calls: 1 },
      ],
      priced: true,
      rates: {
        inputPer1MTokens: 5,
        outputPer1MTokens: 15,
        cacheReadPer1MTokens: 0.5,
        cacheCreationPer1MTokens: 6.25,
      },
    },
    // A model with NO price-table entry — the explicit AC3 "unpriced" state.
    // Token counts are still real; every cost field must render null, never $0.
    {
      provider: 'AzureOpenAI',
      model: 'gpt-5.4-mini',
      calls: 1,
      inputTokens: 500,
      outputTokens: 120,
      cacheReadInputTokens: 0,
      cacheCreationInputTokens: 0,
      latencyTotalMs: 1_400,
      latencyMaxMs: 1_400,
      guardResults: [{ result: 'pass', calls: 1 }],
      priced: false,
      rates: null,
    },
    // A thin/partly-null stored payload — empty provider/model. The call
    // still cost money and is still counted; render honestly as unattributed.
    {
      provider: '',
      model: '',
      calls: 1,
      inputTokens: 50,
      outputTokens: 10,
      cacheReadInputTokens: 0,
      cacheCreationInputTokens: 0,
      latencyTotalMs: 900,
      latencyMaxMs: 900,
      guardResults: [{ result: 'drop', calls: 1 }],
      priced: false,
      rates: null,
    },
  ]

  // Ordered by call count descending, then provider, then model — mirrors
  // the backend's own `byModel`/`cost.byModel` ordering contract (AC2: "the
  // busiest model is first") rather than relying on the seed list above
  // happening to be written in that order.
  const orderedSeeds = [...seeds].sort((a, b) => {
    if (a.calls !== b.calls) return b.calls - a.calls
    if (a.provider !== b.provider) return a.provider < b.provider ? -1 : 1
    return a.model < b.model ? -1 : a.model > b.model ? 1 : 0
  })

  const byModel = orderedSeeds.map(seed => {
    const counts = recencyWeightedDistribution(bucketCount, seed.calls)
    return {
      provider: seed.provider,
      model: seed.model,
      totals: {
        calls: seed.calls,
        inputTokens: seed.inputTokens,
        outputTokens: seed.outputTokens,
        cacheReadInputTokens: seed.cacheReadInputTokens,
        cacheCreationInputTokens: seed.cacheCreationInputTokens,
        latency: {
          totalMs: seed.latencyTotalMs,
          averageMs: seed.calls > 0 ? round6(seed.latencyTotalMs / seed.calls) : 0,
          maxMs: seed.latencyMaxMs,
        },
      },
      guardResults: seed.guardResults,
      buckets: bucketsFor(starts, counts),
      _bucketCounts: counts,
    }
  })

  const overallBucketCounts = starts.map((_, i) =>
    byModel.reduce((sum, m) => sum + (m._bucketCounts[i] ?? 0), 0),
  )
  const totalCalls = seeds.reduce((sum, s) => sum + s.calls, 0)
  const totalInput = seeds.reduce((sum, s) => sum + s.inputTokens, 0)
  const totalOutput = seeds.reduce((sum, s) => sum + s.outputTokens, 0)
  const totalCacheRead = seeds.reduce((sum, s) => sum + s.cacheReadInputTokens, 0)
  const totalCacheCreation = seeds.reduce((sum, s) => sum + s.cacheCreationInputTokens, 0)
  const totalLatencyMs = seeds.reduce((sum, s) => sum + s.latencyTotalMs, 0)
  const maxLatencyMs = seeds.reduce((max, s) => Math.max(max, s.latencyMaxMs), 0)

  const guardTotals = new Map<string, number>()
  for (const seed of seeds) {
    for (const g of seed.guardResults) {
      guardTotals.set(g.result, (guardTotals.get(g.result) ?? 0) + g.calls)
    }
  }

  const costByModel = orderedSeeds.map(seed => {
    if (!seed.priced || !seed.rates) {
      return {
        provider: seed.provider,
        model: seed.model,
        priced: false,
        inputCost: null,
        outputCost: null,
        cacheReadCost: null,
        cacheCreationCost: null,
        totalCost: null,
        rates: null,
      }
    }
    const inputCost = round6((seed.inputTokens / RATE_UNIT) * seed.rates.inputPer1MTokens)
    const outputCost = round6((seed.outputTokens / RATE_UNIT) * seed.rates.outputPer1MTokens)
    const cacheReadCost = round6(
      (seed.cacheReadInputTokens / RATE_UNIT) * seed.rates.cacheReadPer1MTokens,
    )
    const cacheCreationCost = round6(
      (seed.cacheCreationInputTokens / RATE_UNIT) * seed.rates.cacheCreationPer1MTokens,
    )
    return {
      provider: seed.provider,
      model: seed.model,
      priced: true,
      inputCost,
      outputCost,
      cacheReadCost,
      cacheCreationCost,
      totalCost: round6(inputCost + outputCost + cacheReadCost + cacheCreationCost),
      rates: seed.rates,
    }
  })

  const pricedTotalCost = round6(costByModel.reduce((sum, m) => sum + (m.totalCost ?? 0), 0))
  const anyUnpriced = costByModel.some(m => !m.priced)

  return {
    window: {
      clock: 'wall-clock',
      fromWallClock,
      toWallClock,
      windowMinutes,
      bucketMinutes,
      bucketCount,
    },
    totals: {
      calls: totalCalls,
      inputTokens: totalInput,
      outputTokens: totalOutput,
      cacheReadInputTokens: totalCacheRead,
      cacheCreationInputTokens: totalCacheCreation,
      latency: {
        totalMs: totalLatencyMs,
        averageMs: totalCalls > 0 ? round6(totalLatencyMs / totalCalls) : 0,
        maxMs: maxLatencyMs,
      },
    },
    buckets: bucketsFor(starts, overallBucketCounts),
    byModel: byModel.map(({ _bucketCounts: _omit, ...rest }) => rest),
    guardResults: Array.from(guardTotals.entries()).map(([result, calls]) => ({ result, calls })),
    cost: {
      currency: 'USD',
      pricedTotalCost,
      anyUnpriced,
      byModel: costByModel,
    },
    // A plausible non-zero count — the mock always exercises the "surface it,
    // never a silently-low number" AC8 state.
    unparseableEvents: 2,
  }
}

// ---------------------------------------------------------------------------
// The per-exercise module-singleton store
// ---------------------------------------------------------------------------

interface EngineUsageState {
  /** `null` until the first GET (live) or the first mock snapshot resolves. */
  readonly usage: EngineUsageDto | null
  /** `true` while at least one issued request for this exercise is still outstanding. */
  readonly loading: boolean
  /** The last relevant failure's display message, or `null`. */
  readonly error: string | null
  /**
   * The window currently SELECTED (may be ahead of what `usage` reflects
   * while a fetch is in flight).
   */
  readonly windowMinutes: number
}

const DEFAULT_STATE: EngineUsageState = {
  usage: null,
  loading: false,
  error: null,
  windowMinutes: DEFAULT_WINDOW_MINUTES,
}

/**
 * Non-reactive bookkeeping alongside the displayed state — kept OUT of the
 * reactive state since it must not itself trigger a re-render. See module
 * header: a single "latest issued wins on landing" sequence number, plus an
 * in-flight COUNT (not a flag) since concurrent GETs are allowed here.
 */
interface EngineUsageInternal {
  nextSeq: number
  appliedSeq: number
  inFlightCount: number
}

function defaultInternal(): EngineUsageInternal {
  return { nextSeq: 0, appliedSeq: 0, inFlightCount: 0 }
}

const stateByExercise = new Map<string, EngineUsageState>()
const internalByExercise = new Map<string, EngineUsageInternal>()
const listeners = new Set<() => void>()

/** Which exercise ids have completed at least one live/mock initial load since mount/invalidate. */
const started = new Set<string>()

function notify(): void {
  for (const listener of listeners) listener()
}

function getSnapshot(exerciseId: string): EngineUsageState {
  return stateByExercise.get(exerciseId) ?? DEFAULT_STATE
}

function getInternal(exerciseId: string): EngineUsageInternal {
  let internal = internalByExercise.get(exerciseId)
  if (!internal) {
    internal = defaultInternal()
    internalByExercise.set(exerciseId, internal)
  }
  return internal
}

function setFor(exerciseId: string, next: EngineUsageState): void {
  stateByExercise.set(exerciseId, next)
  notify()
}

function subscribe(listener: () => void): () => void {
  listeners.add(listener)
  return () => {
    listeners.delete(listener)
  }
}

/** Clears every exercise's state, internal bookkeeping, and listeners. Test-only. */
function resetForTests(): void {
  stateByExercise.clear()
  internalByExercise.clear()
  started.clear()
  listeners.clear()
}

/**
 * Injects a usage snapshot directly for `exerciseId`, bypassing both the mock
 * default and any live fetch — test-only, mirrors `engineSettingsStore`'s
 * `setForTests`. Marks the exercise as already-started so a subsequently
 * mounted hook does not trigger its own mount-effect fetch behind the
 * caller's back.
 */
function setForTests(
  exerciseId: string,
  usage: EngineUsageDto,
  windowMinutes = usage.window.windowMinutes,
): void {
  setFor(exerciseId, { usage, loading: false, error: null, windowMinutes })
  internalByExercise.set(exerciseId, defaultInternal())
  started.add(exerciseId)
}

/** The module-singleton engine-usage store. Test-only reset/injection. */
export const engineUsageStore = { getSnapshot, subscribe, resetForTests, setForTests }

// ---------------------------------------------------------------------------
// Issue / apply — the one sequencing guard (see module header)
// ---------------------------------------------------------------------------

function issue(exerciseId: string): number {
  const internal = getInternal(exerciseId)
  internal.inFlightCount += 1
  internal.nextSeq += 1
  return internal.nextSeq
}

/**
 * Applies `mySeq` as the newest landed response only if strictly newer than
 * what's already applied.
 */
function tryApply(exerciseId: string, mySeq: number): boolean {
  const internal = getInternal(exerciseId)
  if (mySeq <= internal.appliedSeq) return false
  internal.appliedSeq = mySeq
  return true
}

function settle(exerciseId: string): void {
  const internal = getInternal(exerciseId)
  internal.inFlightCount = Math.max(0, internal.inFlightCount - 1)
}

function isLoading(exerciseId: string): boolean {
  return getInternal(exerciseId).inFlightCount > 0
}

// ---------------------------------------------------------------------------
// Fetch (live) / snapshot (mock)
// ---------------------------------------------------------------------------

function runLiveFetch(exerciseId: string, windowMinutes: number): void {
  started.add(exerciseId)
  const mySeq = issue(exerciseId)
  const current = getSnapshot(exerciseId)
  setFor(exerciseId, { ...current, windowMinutes, loading: true })

  const wireWindow = windowMinutes === DEFAULT_WINDOW_MINUTES ? undefined : windowMinutes

  fetchUsage(wireWindow)
    .then(usage => {
      const applied = tryApply(exerciseId, mySeq)
      settle(exerciseId)
      const latest = getSnapshot(exerciseId)
      setFor(
        exerciseId,
        applied
          ? { ...latest, usage, error: null, loading: isLoading(exerciseId) }
          : { ...latest, loading: isLoading(exerciseId) },
      )
    })
    .catch((error: unknown) => {
      const applied = tryApply(exerciseId, mySeq)
      settle(exerciseId)
      const latest = getSnapshot(exerciseId)
      if (!applied) {
        setFor(exerciseId, { ...latest, loading: isLoading(exerciseId) })
        return
      }
      // A transient failure must not be a PERMANENT dead end for the mount
      // effect — allow a later mount/invalidate to retry (mirrors
      // `useEngineSettings`'s WR-004).
      started.delete(exerciseId)
      const described = describeUsageError(error)
      setFor(exerciseId, { ...latest, error: described.message, loading: isLoading(exerciseId) })
    })
}

function runMockSnapshot(exerciseId: string, windowMinutes: number): void {
  started.add(exerciseId)
  const current = getSnapshot(exerciseId)
  const usage = buildMockEngineUsage(windowMinutes, Date.now())
  setFor(exerciseId, { ...current, usage, windowMinutes, loading: false, error: null })
}

function ensureStarted(exerciseId: string): void {
  if (started.has(exerciseId)) return
  const windowMinutes = getSnapshot(exerciseId).windowMinutes
  if (USE_MOCK_DATA) {
    runMockSnapshot(exerciseId, windowMinutes)
  } else {
    runLiveFetch(exerciseId, windowMinutes)
  }
}

function requestWindow(exerciseId: string, windowMinutes: number): void {
  if (USE_MOCK_DATA) {
    runMockSnapshot(exerciseId, windowMinutes)
    return
  }
  runLiveFetch(exerciseId, windowMinutes)
}

/**
 * A no-op under mock (mirrors `useEngineSettings`'s `invalidate()`) — there is
 * no server to go stale, so re-generating the snapshot here would only
 * discard whatever a test (or a future caller) deliberately set via
 * {@link engineUsageStore}'s `setForTests`. `setWindowMinutes` is the one mock
 * path that DOES regenerate — selecting a different window is an explicit
 * user action (the same "instant apply, no server to race" treatment
 * `useEngineSettings`'s mutations get), not a passive freshness ping.
 */
function refreshCurrent(exerciseId: string): void {
  if (USE_MOCK_DATA) return
  const { windowMinutes } = getSnapshot(exerciseId)
  requestWindow(exerciseId, windowMinutes)
}

// ---------------------------------------------------------------------------
// The hook
// ---------------------------------------------------------------------------

/** The surface `<UsagePanel>` binds to. */
export interface UseEngineUsageResult {
  /** The current usage rollup. `null` only while the initial load hasn't resolved yet. */
  readonly usage: EngineUsageDto | null
  /** `true` while at least one issued request is still outstanding for this exercise. */
  readonly loading: boolean
  /** The last relevant failure's display message, or `null`. */
  readonly error: string | null
  /**
   * The window currently selected (may briefly lead
   * `usage.window.windowMinutes` while a fetch is in flight).
   */
  readonly windowMinutes: number
  /**
   * Requests a different wall-clock window (one of
   * {@link ENGINE_USAGE_WINDOW_PRESETS_MINUTES}).
   */
  readonly setWindowMinutes: (minutes: number) => void
  /**
   * Forces a fresh read for the CURRENTLY selected window — the panel's only
   * refresh mechanism (no polling, see module header). A NO-OP under mock
   * (there is no server to go stale — mirrors `useEngineSettings.refetch()`).
   */
  readonly refresh: () => void
}

/**
 * The per-exercise AI-generation usage read hook. See the module header for
 * the full mock/live + sequencing contract. Must be called under an
 * `<ExerciseContextProvider>` (fail-closed, via `useExerciseContext()`).
 */
export function useEngineUsage(): UseEngineUsageResult {
  const { exerciseId } = useExerciseContext()

  useEffect(() => {
    ensureStarted(exerciseId)
  }, [exerciseId])

  const state = useSyncExternalStore(subscribe, () => getSnapshot(exerciseId))

  const setWindowMinutesCb = useCallback(
    (minutes: number) => {
      if (getSnapshot(exerciseId).windowMinutes === minutes) return
      requestWindow(exerciseId, minutes)
    },
    [exerciseId],
  )

  const refreshCb = useCallback(() => {
    refreshCurrent(exerciseId)
  }, [exerciseId])

  return {
    usage: state.usage,
    loading: state.loading,
    error: state.error,
    windowMinutes: state.windowMinutes,
    setWindowMinutes: setWindowMinutesCb,
    refresh: refreshCb,
  }
}
