/**
 * features/controller/engine/hooks/useEngineUsage.ts
 * ---------------------------------------------------------------------------
 * The AI-generation usage READ hook (feature: engine-telemetry-tuning, story
 * 03c; ADP-041, D5 §11). STAFF world — pure hook, no UI, no COBRA. Reads
 * `GET /api/engine/usage` (story 03a) — a live-ops volume/cost view over the
 * exercise's `engine.generated` event log, distinct from `useEngineSettings`
 * (which answers "what provider is live NOW", AC1 — this hook never repeats
 * that question; see `<UsagePanel>`'s module header for how the two are kept
 * separate).
 *
 * ## No mutations, so no await-then-apply serialization apparatus
 * Unlike `useEngineSettings` (three mutating endpoints racing on one DTO),
 * this hook only ever GETs — an idempotent read with no side effect to
 * protect. So it deliberately does NOT reuse that hook's full "one request
 * outstanding at a time" queueing model; instead it keeps the ONE guard that
 * model exists to generalize in the first place: a monotonic "latest issued
 * wins on landing" sequence number, so a slow response for an OLDER window
 * selection or an OLDER manual refresh can never overwrite a NEWER one that
 * already landed. Concurrent GETs are allowed to race freely; only landing
 * order is gated. `loading` is a per-exercise IN-FLIGHT COUNT (not a single
 * flag), so it stays `true` for as long as ANY issued request is still
 * outstanding, regardless of how many are in flight at once.
 *
 * ## No auto-refresh polling, AND no fetch-on-console-mount (WR-001)
 * `TelemetryEvents` carries no index on `EventType`, so every read re-scans
 * the exercise's `engine.*` rows — unlike `useEngineSettings` (a cheap
 * indexed read that CAN afford `<EngineSettingsPanel>`'s "refetch on every
 * open" staleness discipline), this hook's mount effect must not fire until
 * an operator actually asks. `<UsagePanel>` enforces that by mounting the
 * component that calls this hook (`UsagePanelBody`) ONLY while the flyout is
 * `open` — so `ensureStarted`'s mount-triggered fetch below runs exactly
 * ONCE per exercise, the first time USAGE is ever opened in that console
 * session, never at console boot and never a second time back-to-back on
 * that same first open. Re-opening later reuses the cached snapshot; the
 * panel's manual "Refresh" button (`refresh()`, below) is the ONLY thing
 * that re-scans after that — there is no timer, and no automatic
 * refetch-on-reopen (a deliberate divergence from `EngineSettingsPanel`,
 * for the re-scan-cost reason above).
 *
 * ## The window (AC2/AC6)
 * `windowMinutes` defaults to the server's own default (60) — deliberately
 * OMITTED from the wire request in that case (`liveEngineUsageActions`'s
 * module header, fact 1: an explicit empty value is a `400`, never a
 * fall-through). Selecting a different preset re-issues a live GET with that
 * value. The window is WALL-CLOCK throughout (COR-053 staff carve-out) — see
 * `EngineUsageWindow.clock`, always `"wall-clock"`, which `<UsagePanel>`
 * labels explicitly rather than leaving a reader to guess the clock.
 *
 * ## MOCK <-> LIVE (`USE_MOCK_DATA`, `@/core/config/mockData`)
 * Mock renders a plausible, DETERMINISTIC snapshot with NO network call,
 * generated by {@link buildMockEngineUsage} for whatever window is currently
 * selected (so the window selector visibly does something even without a
 * backend — useful for UAT, which runs on the mock flag). The mock
 * deliberately exercises every state AC2/AC3/AC8 care about in one snapshot:
 * a priced model (`AzureOpenAI`/`gpt-5.4`, real per-token rates), an UNPRICED
 * model (`AzureOpenAI`/`gpt-5.4-mini`, token counts shown, every cost field
 * `null`), an UNATTRIBUTED row (empty `provider`/`model` — a thin/partly-null
 * stored payload that still cost money), a `re-roll` in the guard mix, and a
 * non-zero `unparseableEvents`. The `Fake` provider row mirrors UAT's real
 * dataset today: real call volume, ZERO tokens (by construction), priced at
 * an honest `$0` (not "unpriced"). SG-006: every seed's calls/tokens/latency
 * genuinely SCALE with `windowMinutes` (see `WINDOW_SCALE`) — UAT runs on
 * this mock flag, so a selector whose five presets all showed the identical
 * 46 calls would read as broken, not as a demo.
 *
 * `refresh()` is a NO-OP under mock (mirrors `useEngineSettings.refetch()` —
 * "there is nothing to refetch") — there is no server to go stale, so
 * re-generating the snapshot on every open-transition/manual-refresh would
 * only discard whatever a test (or a future caller) deliberately injected via
 * `engineUsageStore.setForTests`. `setWindowMinutes` is the one mock path
 * that DOES regenerate — selecting a different window is an explicit user
 * action, the same "instant apply, no server to race" treatment
 * `useEngineSettings`'s mutations get, not a passive freshness ping.
 *
 * ## PER-EXERCISE SCOPE (COR-001)
 * Module-singleton store keyed by `exerciseId` — mirrors `useEngineSettings`'s
 * / `useEngineControl`'s shape (`subscribe`/`resetForTests`), so a remount
 * under a different exercise reads a distinct snapshot and no exercise's
 * usage leaks into another's.
 *
 * ## NO TELEMETRY EMITTED HERE
 * This is a read-only observability surface over an existing event log — it
 * introduces no event of its own (AC "Telemetry (XC-004)").
 */

import { useCallback, useEffect, useSyncExternalStore } from 'react'
import { USE_MOCK_DATA } from '@/core/config/mockData'
import { useExerciseContext } from '@/core/exerciseContext'
import {
  describeUsageError,
  getUsage as fetchUsage,
  type EngineUsageDto,
  type EngineUsageRates,
} from '../services/liveEngineUsageActions'

export type {
  EngineUsageBucket,
  EngineUsageCost,
  EngineUsageDto,
  EngineUsageGuardResult,
  EngineUsageLatency,
  EngineUsageModel,
  EngineUsageModelCost,
  EngineUsageRates,
  EngineUsageTotals,
  EngineUsageWindow,
} from '../services/liveEngineUsageActions'

/**
 * The window presets `<UsagePanel>` offers — every one the backend documents
 * as evenly-bucketed (SG-001).
 */
export const ENGINE_USAGE_WINDOW_PRESETS_MINUTES = [1, 15, 60, 240, 1440] as const

/**
 * The server's own default window (`EngineUsageAggregator.DefaultWindowMinutes`)
 * — sent by OMISSION, never as an explicit value.
 */
export const DEFAULT_WINDOW_MINUTES = 60

const MAX_BUCKETS = 60

// ---------------------------------------------------------------------------
// The mock usage snapshot generator
// ---------------------------------------------------------------------------

/**
 * The geometry {@link buildBucketGeometry} derives from a window — bucket
 * starts + width + the window's own bounds.
 */
interface MockBucketGeometry {
  readonly starts: readonly string[]
  readonly bucketMinutes: number
  readonly fromWallClock: string
  readonly toWallClock: string
}

/**
 * Mirrors `EngineUsageAggregator.BuildWindow`'s bucket-ceiling geometry
 * (server contract, `EngineUsageAggregator.cs`).
 */
function buildBucketGeometry(nowMs: number, windowMinutes: number): MockBucketGeometry {
  const bucketMinutes = Math.max(1, Math.ceil(windowMinutes / MAX_BUCKETS))
  const bucketCount = Math.max(1, Math.ceil(windowMinutes / bucketMinutes))
  const fromMs = nowMs - windowMinutes * 60_000
  const starts: string[] = []
  for (let i = 0; i < bucketCount; i += 1) {
    starts.push(new Date(fromMs + i * bucketMinutes * 60_000).toISOString())
  }
  return {
    starts,
    bucketMinutes,
    fromWallClock: new Date(fromMs).toISOString(),
    toWallClock: new Date(nowMs).toISOString(),
  }
}

/**
 * Deterministically distributes `total` calls across `bucketCount` buckets,
 * weighted toward the MOST RECENT buckets (a burstier, more "live" look than
 * a flat spread) — the remainder always lands on the recency-weighted side so
 * `sum(result) === total` exactly, never approximately.
 */
function recencyWeightedDistribution(bucketCount: number, total: number): number[] {
  if (bucketCount <= 0) return []
  if (total <= 0) return new Array(bucketCount).fill(0)

  const weights = Array.from({ length: bucketCount }, (_, i) => i + 1)
  const weightSum = weights.reduce((sum, w) => sum + w, 0)
  const floored = weights.map(w => Math.floor((w / weightSum) * total))
  let remainder = total - floored.reduce((sum, c) => sum + c, 0)
  for (let i = floored.length - 1; i >= 0 && remainder > 0; i -= 1) {
    floored[i] = (floored[i] ?? 0) + 1
    remainder -= 1
  }
  return floored
}

function bucketsFor(starts: readonly string[], counts: readonly number[]) {
  return starts.map((startWallClock, i) => ({ startWallClock, calls: counts[i] ?? 0 }))
}

/** One guard-result/call-count pair, in either a seed's or a rollup's shape. */
interface MockGuardSplit {
  readonly result: string
  readonly calls: number
}

/**
 * One synthetic model's BASE (60-minute-window) shape. `guardSplit` is a
 * FUNCTION of the (already window-scaled) call count rather than a fixed
 * array, so a scaled-down call count (e.g. the 1-minute preset) still sums
 * exactly to itself instead of silently drifting from the invariant
 * `sum(guardResults.calls) === totals.calls` (SG-006).
 */
interface MockModelSeed {
  readonly provider: string
  readonly model: string
  readonly baseCalls: number
  readonly baseInputTokens: number
  readonly baseOutputTokens: number
  readonly baseCacheReadInputTokens: number
  readonly baseCacheCreationInputTokens: number
  readonly baseLatencyTotalMs: number
  /** NOT scaled with the window — a plausible single-call ceiling regardless of volume. */
  readonly latencyMaxMs: number
  readonly guardSplit: (calls: number) => readonly MockGuardSplit[]
  readonly priced: boolean
  readonly rates: EngineUsageRates | null
}

/** One resolved (window-scaled, concrete-numbers) model row, before ordering/bucketing. */
interface ResolvedMockModel {
  readonly provider: string
  readonly model: string
  readonly calls: number
  readonly inputTokens: number
  readonly outputTokens: number
  readonly cacheReadInputTokens: number
  readonly cacheCreationInputTokens: number
  readonly latencyTotalMs: number
  readonly latencyMaxMs: number
  readonly guardResults: readonly MockGuardSplit[]
  readonly priced: boolean
  readonly rates: EngineUsageRates | null
}

const RATE_UNIT = 1_000_000

function round6(value: number): number {
  return Math.round(value * 1_000_000) / 1_000_000
}

/**
 * S-4: rounds a latency figure to 3dp, mirroring the backend's own
 * `EngineUsageAggregator.LatencyDecimals` — kills the float-artifact class
 * (`baseLatencyTotalMs * factor` producing a long tail) even though
 * `formatMs` already caps display at 2dp; benign today, but a scaled value
 * shouldn't need a display-layer cap to look honest.
 */
function round3(value: number): number {
  return Math.round(value * 1_000) / 1_000
}

/**
 * SG-006: the mock's own call-volume scale relative to {@link DEFAULT_WINDOW_MINUTES}
 * (the 60-minute base every seed below is written against) — so selecting a
 * different preset under `USE_MOCK_DATA` visibly changes calls/tokens/cost,
 * not just the bucket count. Not linear at the extremes (a literal 1/60th of
 * a 60-minute burst would round every seed to 0, silently dropping the
 * priced/unpriced/re-roll/unattributed states this mock exists to
 * demonstrate) — chosen so every preset still shows every state.
 */
const WINDOW_SCALE: Readonly<Record<number, number>> = {
  1: 0.05,
  15: 0.4,
  60: 1,
  240: 3,
  1440: 12,
}

function windowScaleFactor(windowMinutes: number): number {
  return WINDOW_SCALE[windowMinutes] ?? windowMinutes / DEFAULT_WINDOW_MINUTES
}

/**
 * Scales a token/latency quantity — `0` stays `0` (the Fake provider's
 * tokens, by construction).
 */
function scaleQuantity(base: number, factor: number): number {
  return Math.round(base * factor)
}

/**
 * Scales a call count — floored at `1` (never `0`) whenever the base is
 * positive, so every seed stays visible at every window preset.
 */
function scaleCalls(base: number, factor: number): number {
  if (base <= 0) return 0
  return Math.max(1, Math.round(base * factor))
}

/**
 * SG-001: orders guard-result rows by call count descending, then result
 * ordinal — mirrors the backend's actual `OrderByDescending(calls)
 * .ThenBy(result, Ordinal)` contract (`EngineUsageAggregator.ProjectGuardResults`),
 * the SAME discipline `orderModels` below already applies to `byModel`.
 * Applied to BOTH the per-model and the aggregate guard-result arrays — a
 * fixed seed/insertion order would only match the real contract by accident.
 */
function sortGuardResults(entries: readonly MockGuardSplit[]): MockGuardSplit[] {
  return [...entries].sort((a, b) => {
    if (a.calls !== b.calls) return b.calls - a.calls
    return a.result < b.result ? -1 : a.result > b.result ? 1 : 0
  })
}

/**
 * Orders resolved model rows by call count descending, then provider, then
 * model — mirrors the backend's `byModel`/`cost.byModel` contract (AC2: "the
 * busiest model is first").
 */
function orderModels(models: readonly ResolvedMockModel[]): ResolvedMockModel[] {
  return [...models].sort((a, b) => {
    if (a.calls !== b.calls) return b.calls - a.calls
    if (a.provider !== b.provider) return a.provider < b.provider ? -1 : 1
    return a.model < b.model ? -1 : a.model > b.model ? 1 : 0
  })
}

/**
 * The BASE (60-minute) seed data every window preset scales from (SG-006).
 * Static — module-level, not a function of `windowMinutes`/`nowMs`.
 */
const RAW_MODEL_SEEDS: readonly MockModelSeed[] = [
  // The Fake provider — mirrors UAT's real dataset today: real volume, ZERO
  // tokens by construction, priced at an honest $0 (never "unpriced" — the
  // price table DOES have an entry, it's just all zeros).
  {
    provider: 'Fake',
    model: 'fake-deterministic',
    baseCalls: 40,
    baseInputTokens: 0,
    baseOutputTokens: 0,
    baseCacheReadInputTokens: 0,
    baseCacheCreationInputTokens: 0,
    baseLatencyTotalMs: 0.8,
    latencyMaxMs: 0.05,
    guardSplit: calls => [{ result: 'pass', calls }],
    priced: true,
    rates: {
      inputPer1MTokens: 0,
      outputPer1MTokens: 0,
      cacheReadPer1MTokens: 0,
      cacheCreationPer1MTokens: 0,
    },
  },
  // A priced live model, including a re-roll (a call that cost money and
  // produced nothing — counted, never dropped) — at least one re-roll
  // survives scaling down to a single call.
  {
    provider: 'AzureOpenAI',
    model: 'gpt-5.4',
    baseCalls: 4,
    baseInputTokens: 8_000,
    baseOutputTokens: 2_000,
    baseCacheReadInputTokens: 300,
    baseCacheCreationInputTokens: 40,
    baseLatencyTotalMs: 9_200,
    latencyMaxMs: 3_100,
    guardSplit: calls => {
      const reRoll = Math.min(calls, Math.max(1, Math.round(calls * 0.25)))
      const pass = calls - reRoll
      return pass > 0
        ? [{ result: 'pass', calls: pass }, { result: 're-roll', calls: reRoll }]
        : [{ result: 're-roll', calls: reRoll }]
    },
    priced: true,
    rates: {
      inputPer1MTokens: 5,
      outputPer1MTokens: 15,
      cacheReadPer1MTokens: 0.5,
      cacheCreationPer1MTokens: 6.25,
    },
  },
  // A model with NO price-table entry — the explicit AC3 "unpriced" state.
  // Token counts are still real; every cost field must render null, never $0.
  {
    provider: 'AzureOpenAI',
    model: 'gpt-5.4-mini',
    baseCalls: 1,
    baseInputTokens: 500,
    baseOutputTokens: 120,
    baseCacheReadInputTokens: 0,
    baseCacheCreationInputTokens: 0,
    baseLatencyTotalMs: 1_400,
    latencyMaxMs: 1_400,
    guardSplit: calls => [{ result: 'pass', calls }],
    priced: false,
    rates: null,
  },
  // A thin/partly-null stored payload — empty provider/model. The call
  // still cost money and is still counted; render honestly as unattributed.
  {
    provider: '',
    model: '',
    baseCalls: 1,
    baseInputTokens: 50,
    baseOutputTokens: 10,
    baseCacheReadInputTokens: 0,
    baseCacheCreationInputTokens: 0,
    baseLatencyTotalMs: 900,
    latencyMaxMs: 900,
    guardSplit: calls => [{ result: 'drop', calls }],
    priced: false,
    rates: null,
  },
]

/**
 * Builds a plausible, deterministic `EngineUsageDto` for `windowMinutes` as
 * of `nowMs` — no network call. See this module's header for exactly which
 * states this snapshot exercises and why (AC2/AC3/AC8), and {@link WINDOW_SCALE}
 * for why volume/cost genuinely differ across window presets (SG-006).
 */
export function buildMockEngineUsage(windowMinutes: number, nowMs: number): EngineUsageDto {
  const { starts, bucketMinutes, fromWallClock, toWallClock } = buildBucketGeometry(
    nowMs,
    windowMinutes,
  )
  const bucketCount = starts.length
  const factor = windowScaleFactor(windowMinutes)

  const resolvedModels: readonly ResolvedMockModel[] = RAW_MODEL_SEEDS.map(seed => {
    const calls = scaleCalls(seed.baseCalls, factor)
    // S-4: round to 3dp, mirroring the backend's own latency rounding.
    const latencyTotalMs = round3(seed.baseLatencyTotalMs * factor)
    const latencyAverageMs = calls > 0 ? latencyTotalMs / calls : 0
    // W-2: `latencyMaxMs` is a running max over the SAME calls that build
    // `latencyTotalMs` — structurally, `avg <= max <= total` always (the
    // backend gets this for free, `EngineUsageAggregator`'s max accumulator
    // runs over the calls it also sums). The seed's fixed ceiling does NOT
    // scale with the window factor (a "busiest single call" figure has no
    // reason to shrink just because fewer calls are shown), but at a small
    // enough factor that fixed ceiling can exceed the now-shrunk total —
    // clamping down to `total` (never below `avg`) keeps both invariants
    // true at every window, and collapses to max === avg === total exactly
    // when there is only one call (the only mathematically valid answer).
    const latencyMaxMs = Math.min(latencyTotalMs, Math.max(latencyAverageMs, seed.latencyMaxMs))
    return {
      provider: seed.provider,
      model: seed.model,
      calls,
      inputTokens: scaleQuantity(seed.baseInputTokens, factor),
      outputTokens: scaleQuantity(seed.baseOutputTokens, factor),
      cacheReadInputTokens: scaleQuantity(seed.baseCacheReadInputTokens, factor),
      cacheCreationInputTokens: scaleQuantity(seed.baseCacheCreationInputTokens, factor),
      latencyTotalMs,
      latencyMaxMs,
      guardResults: sortGuardResults(seed.guardSplit(calls)),
      priced: seed.priced,
      rates: seed.rates,
    }
  })

  const orderedModels = orderModels(resolvedModels)

  const byModel = orderedModels.map(model => {
    const counts = recencyWeightedDistribution(bucketCount, model.calls)
    return {
      provider: model.provider,
      model: model.model,
      totals: {
        calls: model.calls,
        inputTokens: model.inputTokens,
        outputTokens: model.outputTokens,
        cacheReadInputTokens: model.cacheReadInputTokens,
        cacheCreationInputTokens: model.cacheCreationInputTokens,
        latency: {
          totalMs: model.latencyTotalMs,
          // S-4: 3dp, matching the backend's `LatencyDecimals` for every
          // latency field (total/average/max) — `round6` is reserved for
          // currency (the backend's separate `CostDecimals`).
          averageMs: model.calls > 0 ? round3(model.latencyTotalMs / model.calls) : 0,
          maxMs: model.latencyMaxMs,
        },
      },
      guardResults: model.guardResults,
      buckets: bucketsFor(starts, counts),
      _bucketCounts: counts,
    }
  })

  const overallBucketCounts = starts.map((_, i) =>
    byModel.reduce((sum, m) => sum + (m._bucketCounts[i] ?? 0), 0),
  )
  const totalCalls = resolvedModels.reduce((sum, m) => sum + m.calls, 0)
  const totalInput = resolvedModels.reduce((sum, m) => sum + m.inputTokens, 0)
  const totalOutput = resolvedModels.reduce((sum, m) => sum + m.outputTokens, 0)
  const totalCacheRead = resolvedModels.reduce((sum, m) => sum + m.cacheReadInputTokens, 0)
  const totalCacheCreation = resolvedModels.reduce((sum, m) => sum + m.cacheCreationInputTokens, 0)
  // S-4: rounded to 3dp (mirrors the backend). W-2: `maxLatencyMs` is the max
  // of the PER-MODEL max values, each of which is already clamped to its own
  // `avg <= max <= total` — the true global max (across every individual
  // call from every model) equals the max of the per-model maxes, so no
  // separate aggregate-level clamp is needed; it inherits both invariants
  // transitively (max <= total: each per-model max <= that model's own
  // total <= the summed total; avg <= max: a basic fact about any nonempty
  // set of non-negative numbers).
  const totalLatencyMs = round3(resolvedModels.reduce((sum, m) => sum + m.latencyTotalMs, 0))
  const maxLatencyMs = round3(resolvedModels.reduce((max, m) => Math.max(max, m.latencyMaxMs), 0))

  const guardTotals = new Map<string, number>()
  for (const model of resolvedModels) {
    for (const g of model.guardResults) {
      guardTotals.set(g.result, (guardTotals.get(g.result) ?? 0) + g.calls)
    }
  }

  const costByModel = orderedModels.map(model => {
    if (!model.priced || !model.rates) {
      return {
        provider: model.provider,
        model: model.model,
        priced: false,
        inputCost: null,
        outputCost: null,
        cacheReadCost: null,
        cacheCreationCost: null,
        totalCost: null,
        rates: null,
      }
    }
    const inputCost = round6((model.inputTokens / RATE_UNIT) * model.rates.inputPer1MTokens)
    const outputCost = round6((model.outputTokens / RATE_UNIT) * model.rates.outputPer1MTokens)
    const cacheReadCost = round6(
      (model.cacheReadInputTokens / RATE_UNIT) * model.rates.cacheReadPer1MTokens,
    )
    const cacheCreationCost = round6(
      (model.cacheCreationInputTokens / RATE_UNIT) * model.rates.cacheCreationPer1MTokens,
    )
    return {
      provider: model.provider,
      model: model.model,
      priced: true,
      inputCost,
      outputCost,
      cacheReadCost,
      cacheCreationCost,
      totalCost: round6(inputCost + outputCost + cacheReadCost + cacheCreationCost),
      rates: model.rates,
    }
  })

  const pricedTotalCost = round6(costByModel.reduce((sum, m) => sum + (m.totalCost ?? 0), 0))
  const anyUnpriced = costByModel.some(m => !m.priced)

  return {
    window: {
      clock: 'wall-clock',
      fromWallClock,
      toWallClock,
      windowMinutes,
      bucketMinutes,
      bucketCount,
    },
    totals: {
      calls: totalCalls,
      inputTokens: totalInput,
      outputTokens: totalOutput,
      cacheReadInputTokens: totalCacheRead,
      cacheCreationInputTokens: totalCacheCreation,
      latency: {
        totalMs: totalLatencyMs,
        averageMs: totalCalls > 0 ? round3(totalLatencyMs / totalCalls) : 0,
        maxMs: maxLatencyMs,
      },
    },
    buckets: bucketsFor(starts, overallBucketCounts),
    byModel: byModel.map(({ _bucketCounts: _omit, ...rest }) => rest),
    guardResults: sortGuardResults(
      Array.from(guardTotals.entries()).map(([result, calls]) => ({ result, calls })),
    ),
    cost: {
      currency: 'USD',
      pricedTotalCost,
      anyUnpriced,
      byModel: costByModel,
    },
    // A plausible non-zero count — the mock always exercises the "surface it,
    // never a silently-low number" AC8 state.
    unparseableEvents: 2,
  }
}

// ---------------------------------------------------------------------------
// The per-exercise module-singleton store
// ---------------------------------------------------------------------------

interface EngineUsageState {
  /** `null` until the first GET (live) or the first mock snapshot resolves. */
  readonly usage: EngineUsageDto | null
  /** `true` while at least one issued request for this exercise is still outstanding. */
  readonly loading: boolean
  /** The last relevant failure's display message, or `null`. */
  readonly error: string | null
  /**
   * The window currently SELECTED (may be ahead of what `usage` reflects
   * while a fetch is in flight).
   */
  readonly windowMinutes: number
}

const DEFAULT_STATE: EngineUsageState = {
  usage: null,
  loading: false,
  error: null,
  windowMinutes: DEFAULT_WINDOW_MINUTES,
}

/**
 * Non-reactive bookkeeping alongside the displayed state — kept OUT of the
 * reactive state since it must not itself trigger a re-render. See module
 * header: a single "latest issued wins on landing" sequence number, plus an
 * in-flight COUNT (not a flag) since concurrent GETs are allowed here.
 */
interface EngineUsageInternal {
  nextSeq: number
  appliedSeq: number
  inFlightCount: number
}

function defaultInternal(): EngineUsageInternal {
  return { nextSeq: 0, appliedSeq: 0, inFlightCount: 0 }
}

const stateByExercise = new Map<string, EngineUsageState>()
const internalByExercise = new Map<string, EngineUsageInternal>()
const listeners = new Set<() => void>()

/** Which exercise ids have completed at least one live/mock initial load since mount/invalidate. */
const started = new Set<string>()

function notify(): void {
  for (const listener of listeners) listener()
}

function getSnapshot(exerciseId: string): EngineUsageState {
  return stateByExercise.get(exerciseId) ?? DEFAULT_STATE
}

function getInternal(exerciseId: string): EngineUsageInternal {
  let internal = internalByExercise.get(exerciseId)
  if (!internal) {
    internal = defaultInternal()
    internalByExercise.set(exerciseId, internal)
  }
  return internal
}

function setFor(exerciseId: string, next: EngineUsageState): void {
  stateByExercise.set(exerciseId, next)
  notify()
}

function subscribe(listener: () => void): () => void {
  listeners.add(listener)
  return () => {
    listeners.delete(listener)
  }
}

/** Clears every exercise's state, internal bookkeeping, and listeners. Test-only. */
function resetForTests(): void {
  stateByExercise.clear()
  internalByExercise.clear()
  started.clear()
  listeners.clear()
}

/**
 * Injects a usage snapshot directly for `exerciseId`, bypassing both the mock
 * default and any live fetch — test-only, mirrors `engineSettingsStore`'s
 * `setForTests`. Marks the exercise as already-started so a subsequently
 * mounted hook does not trigger its own mount-effect fetch behind the
 * caller's back.
 */
function setForTests(
  exerciseId: string,
  usage: EngineUsageDto,
  windowMinutes = usage.window.windowMinutes,
): void {
  setFor(exerciseId, { usage, loading: false, error: null, windowMinutes })
  internalByExercise.set(exerciseId, defaultInternal())
  started.add(exerciseId)
}

/** The module-singleton engine-usage store. Test-only reset/injection. */
export const engineUsageStore = { getSnapshot, subscribe, resetForTests, setForTests }

// ---------------------------------------------------------------------------
// Issue / apply — the one sequencing guard (see module header)
// ---------------------------------------------------------------------------

function issue(exerciseId: string): number {
  const internal = getInternal(exerciseId)
  internal.inFlightCount += 1
  internal.nextSeq += 1
  return internal.nextSeq
}

/**
 * Applies `mySeq` as the newest landed response only if strictly newer than
 * what's already applied.
 */
function tryApply(exerciseId: string, mySeq: number): boolean {
  const internal = getInternal(exerciseId)
  if (mySeq <= internal.appliedSeq) return false
  internal.appliedSeq = mySeq
  return true
}

function settle(exerciseId: string): void {
  const internal = getInternal(exerciseId)
  internal.inFlightCount = Math.max(0, internal.inFlightCount - 1)
}

function isLoading(exerciseId: string): boolean {
  return getInternal(exerciseId).inFlightCount > 0
}

// ---------------------------------------------------------------------------
// Fetch (live) / snapshot (mock)
// ---------------------------------------------------------------------------

function runLiveFetch(exerciseId: string, windowMinutes: number): void {
  started.add(exerciseId)
  const mySeq = issue(exerciseId)
  const current = getSnapshot(exerciseId)
  setFor(exerciseId, { ...current, windowMinutes, loading: true })

  const wireWindow = windowMinutes === DEFAULT_WINDOW_MINUTES ? undefined : windowMinutes

  fetchUsage(wireWindow)
    .then(usage => {
      const applied = tryApply(exerciseId, mySeq)
      settle(exerciseId)
      const latest = getSnapshot(exerciseId)
      setFor(
        exerciseId,
        applied
          ? { ...latest, usage, error: null, loading: isLoading(exerciseId) }
          : { ...latest, loading: isLoading(exerciseId) },
      )
    })
    .catch((error: unknown) => {
      const applied = tryApply(exerciseId, mySeq)
      settle(exerciseId)
      const latest = getSnapshot(exerciseId)
      if (!applied) {
        setFor(exerciseId, { ...latest, loading: isLoading(exerciseId) })
        return
      }
      // A transient failure must not be a PERMANENT dead end for the mount
      // effect — allow a later mount/invalidate to retry (mirrors
      // `useEngineSettings`'s WR-004).
      started.delete(exerciseId)
      const described = describeUsageError(error)
      setFor(exerciseId, { ...latest, error: described.message, loading: isLoading(exerciseId) })
    })
}

function runMockSnapshot(exerciseId: string, windowMinutes: number): void {
  started.add(exerciseId)
  const current = getSnapshot(exerciseId)
  const usage = buildMockEngineUsage(windowMinutes, Date.now())
  setFor(exerciseId, { ...current, usage, windowMinutes, loading: false, error: null })
}

function ensureStarted(exerciseId: string): void {
  if (started.has(exerciseId)) return
  const windowMinutes = getSnapshot(exerciseId).windowMinutes
  if (USE_MOCK_DATA) {
    runMockSnapshot(exerciseId, windowMinutes)
  } else {
    runLiveFetch(exerciseId, windowMinutes)
  }
}

function requestWindow(exerciseId: string, windowMinutes: number): void {
  if (USE_MOCK_DATA) {
    runMockSnapshot(exerciseId, windowMinutes)
    return
  }
  runLiveFetch(exerciseId, windowMinutes)
}

/**
 * A no-op under mock (mirrors `useEngineSettings`'s `invalidate()`) — there is
 * no server to go stale, so re-generating the snapshot here would only
 * discard whatever a test (or a future caller) deliberately set via
 * {@link engineUsageStore}'s `setForTests`. `setWindowMinutes` is the one mock
 * path that DOES regenerate — selecting a different window is an explicit
 * user action (the same "instant apply, no server to race" treatment
 * `useEngineSettings`'s mutations get), not a passive freshness ping.
 */
function refreshCurrent(exerciseId: string): void {
  if (USE_MOCK_DATA) return
  const { windowMinutes } = getSnapshot(exerciseId)
  requestWindow(exerciseId, windowMinutes)
}

// ---------------------------------------------------------------------------
// The hook
// ---------------------------------------------------------------------------

/** The surface `<UsagePanel>` binds to. */
export interface UseEngineUsageResult {
  /** The current usage rollup. `null` only while the initial load hasn't resolved yet. */
  readonly usage: EngineUsageDto | null
  /** `true` while at least one issued request is still outstanding for this exercise. */
  readonly loading: boolean
  /** The last relevant failure's display message, or `null`. */
  readonly error: string | null
  /**
   * The window currently selected (may briefly lead
   * `usage.window.windowMinutes` while a fetch is in flight).
   */
  readonly windowMinutes: number
  /**
   * Requests a different wall-clock window (one of
   * {@link ENGINE_USAGE_WINDOW_PRESETS_MINUTES}).
   */
  readonly setWindowMinutes: (minutes: number) => void
  /**
   * Forces a fresh read for the CURRENTLY selected window — the panel's only
   * refresh mechanism (no polling, see module header). A NO-OP under mock
   * (there is no server to go stale — mirrors `useEngineSettings.refetch()`).
   */
  readonly refresh: () => void
}

/**
 * The per-exercise AI-generation usage read hook. See the module header for
 * the full mock/live + sequencing contract. Must be called under an
 * `<ExerciseContextProvider>` (fail-closed, via `useExerciseContext()`).
 */
export function useEngineUsage(): UseEngineUsageResult {
  const { exerciseId } = useExerciseContext()

  useEffect(() => {
    ensureStarted(exerciseId)
  }, [exerciseId])

  const state = useSyncExternalStore(subscribe, () => getSnapshot(exerciseId))

  const setWindowMinutesCb = useCallback(
    (minutes: number) => {
      if (getSnapshot(exerciseId).windowMinutes === minutes) return
      requestWindow(exerciseId, minutes)
    },
    [exerciseId],
  )

  const refreshCb = useCallback(() => {
    refreshCurrent(exerciseId)
  }, [exerciseId])

  return {
    usage: state.usage,
    loading: state.loading,
    error: state.error,
    windowMinutes: state.windowMinutes,
    setWindowMinutes: setWindowMinutesCb,
    refresh: refreshCb,
  }
}
