/**
 * features/personas/seedCast.ts
 * ---------------------------------------------------------------------------
 * One-action cast seeding (feature: persona-management, story 02; COR-021).
 * `seedCast` instantiates every template in a cast into an exercise-scoped
 * `StaffPersona` — the FULL instance, including the staff-only `personaType`
 * (seeding is a staff/planner action, and the archetype is what drives
 * `deriveJoinedAt` below). Narrowing to the participant `Persona` projection
 * happens at the READ seam (`personaService.toParticipantPersona`), never
 * here — with believable DERIVED STATE a template cannot carry:
 *   - `followerCount` — derived from the template's `audienceBand` (SOC-054)
 *     with a deterministic per-handle jitter (so counts vary but tests are
 *     stable — no Math.random);
 *   - `joinedAt` — a scenario ISO instant PREDATING the exercise (COR-053; the
 *     impersonator / bad-actor joined most recently, mirroring the D1 "joined
 *     this week" beat).
 *
 * Pure and deterministic: it takes the templates explicitly (no hidden global
 * read) and derives everything from stable inputs, so seeding the same cast
 * twice yields identical instances. Staff-only, exercise-scoped action.
 *
 * NOTE on time: `joinedAt` is generated by fixed arithmetic on a FIXED
 * pre-exercise epoch constant — it is authored scenario data, never a read of
 * the wall clock. (This module is not a participant surface, but it still never
 * reads `Date.now()`; the value is a deterministic scenario instant.)
 *
 * MOCK/LIVE PARITY (profiles-social-graph/02+07): a seeded instance ALSO
 * populates `audienceMagnitude` and `followingCount` — not just
 * `followerCount` — even though `types.ts` declares both optional. The live
 * backend (story 07) composes `followerCount = audienceMagnitude + real
 * inbound edges` and separately reports the raw `audienceMagnitude`; anything
 * that reads magnitude directly (`audienceReach()`, `displayedFollowerCount()`
 * — profiles-social-graph/05) needs THAT number, not the already-composed
 * `followerCount`. A freshly seeded instance has zero real follow edges, so
 * its `audienceMagnitude` is exactly `deriveFollowerCount`'s output (the same
 * number `followerCount` used to mean, pre-story-07) and `followingCount` is
 * `0` — the honest seed-time value, not a placeholder. Leaving either
 * `undefined` here would make the MOCK path (`USE_MOCK_DATA`, true in UAT)
 * silently diverge from the live path on every magnitude-dependent surface —
 * exactly the mock-says-one-thing/live-says-another shape that motivated
 * this feature's own bug report — and a divergence only visible in UAT, never
 * in the test suite, since every seedCast test runs mock-shaped by
 * construction.
 */

import type { Cast } from './casts'
import {
  personaIdForHandle,
  type AudienceBand,
  type PersonaTemplate,
  type StaffPersona,
} from './types'

/** Approximate follower floor per audience-magnitude band (SOC-054). */
const BAND_BASE: Record<AudienceBand, number> = {
  nano: 450,
  micro: 4800,
  mid: 46000,
  large: 220000,
  mega: 1500000,
}

/**
 * Fixed pre-exercise epoch (ms) that all seeded join dates precede. A constant
 * so seeding is deterministic and reproducible; it sits before the Fairhaven
 * exercise window. Not a wall-clock read.
 */
const SEED_EPOCH_MS = Date.parse('2026-06-15T12:00:00Z')
const DAY_MS = 24 * 60 * 60 * 1000

/** Small, stable, non-negative string hash (FNV-1a-ish) for deterministic jitter. */
function stableHash(input: string): number {
  let hash = 2166136261
  for (let i = 0; i < input.length; i += 1) {
    hash ^= input.charCodeAt(i)
    hash = Math.imul(hash, 16777619)
  }
  return hash >>> 0
}

/** Derives a varied-but-deterministic follower count from the band + handle. */
function deriveFollowerCount(band: AudienceBand, handle: string): number {
  const base = BAND_BASE[band]
  // Up to +40% deterministic spread so counts within a band differ believably.
  const spread = Math.floor((stableHash(handle) % 400) / 1000 * base)
  return base + spread
}

/**
 * Derives a pre-exercise join instant. Bad actors join RECENTLY (the lookalike
 * "joined this week" tell); everyone else has an established, older account.
 */
function deriveJoinedAt(template: PersonaTemplate): string {
  const isRecent = template.personaType === 'bad-actor'
  const offsetDays = isRecent
    ? 3 + (stableHash(template.handle) % 4) // 3–6 days before the epoch
    : 90 + (stableHash(template.handle) % 640) // ~3 months to ~2 years before
  return new Date(SEED_EPOCH_MS - offsetDays * DAY_MS).toISOString()
}

/**
 * Instantiates `cast` into exercise-scoped persona instances for `exerciseId`.
 * `templates` is the org library to resolve the cast's `templateIds` against
 * (defaults to the seed library). A cast member whose template is missing is
 * skipped rather than throwing — a malformed cast never blocks seeding the rest.
 */
export function seedCast(
  cast: Cast,
  exerciseId: string,
  templates: readonly PersonaTemplate[],
): StaffPersona[] {
  const byId = new Map(templates.map(t => [t.id, t]))

  return cast.templateIds.flatMap(templateId => {
    const template = byId.get(templateId)
    if (!template) return []

    const persona: StaffPersona = {
      id: personaIdForHandle(template.handle),
      exerciseId,
      templateId: template.id,
      displayName: template.displayName,
      handle: template.handle,
      kind: template.kind,
      personaType: template.personaType,
      verified: template.verified,
      avatarColor: template.avatarColor,
      initials: template.initials,
      bio: template.bio,
      audienceBand: template.audienceBand,
      // A freshly seeded instance has NO real follow edges yet, so the
      // composed displayed count (magnitude + real edges) is just the
      // magnitude itself — see the module header's "MOCK/LIVE PARITY" note.
      followerCount: deriveFollowerCount(template.audienceBand, template.handle),
      audienceMagnitude: deriveFollowerCount(template.audienceBand, template.handle),
      followingCount: 0,
      joinedAt: deriveJoinedAt(template),
    }
    return [persona]
  })
}
